### ISSUE TITLE
Contrast Sample Values

### ISSUE THREAD

**Issue by bt7893** [romannurik/Sketch-Contrast#4]
Your plug-in is extremely promising and will save me so much time - Thank you for your amazing work! However, some values does not look accurate when sampled. Values of the same text / background color are giving me mixed results. I have attached screenshots of what I am referring to along with the Sketch file. Thank you once again!

[test_sample_color_contrast.zip](https://github.com/romannurik/Sketch-Contrast/files/2448023/test_sample_color_contrast.zip)

<img width="550" alt="screen shot 2018-10-04 at 2 03 09 pm" src="https://user-images.githubusercontent.com/10103433/46501125-2f9ea180-c7ea-11e8-9a16-5cc4beba628d.png">
<img width="1186" alt="screen shot 2018-10-04 at 2 02 59 pm" src="https://user-images.githubusercontent.com/10103433/46501129-33cabf00-c7ea-11e8-8111-ac6027280606.png">

**Comment by romannurik** [comment]
Thanks so much for filing! Will take a look asap.

**Comment by romannurik** [comment]
Just took a look... it looks like you've got a background gradient, so the background color is actually subtly changing, e.g. #00688F in the middle column and #00648C in the right column. The bottom-right is passing because large text only needs to be 3.0:1 to pass.

A new version of this plugin will start showing yellow 'mixed' results where some points in the text pass while others fail:

![image](https://user-images.githubusercontent.com/100155/46513796-41069e80-c828-11e8-941d-3f8e5a576456.png)
